// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for EditProjectOptionState.
const (
	EditProjectOptionStateClosed EditProjectOptionState = "closed"
	EditProjectOptionStateOpen   EditProjectOptionState = "open"
)

// Defines values for ProjectState.
const (
	ProjectStateClosed ProjectState = "closed"
	ProjectStateOpen   ProjectState = "open"
)

// Defines values for Sort.
const (
	SortAlphabetically        Sort = "alphabetically"
	SortLeastupdate           Sort = "leastupdate"
	SortNewest                Sort = "newest"
	SortOldest                Sort = "oldest"
	SortRecentupdate          Sort = "recentupdate"
	SortReversealphabetically Sort = "reversealphabetically"
)

// Defines values for State.
const (
	StateAll    State = "all"
	StateClosed State = "closed"
	StateOpen   State = "open"
)

// Defines values for ListOrgProjectsParamsState.
const (
	ListOrgProjectsParamsStateAll    ListOrgProjectsParamsState = "all"
	ListOrgProjectsParamsStateClosed ListOrgProjectsParamsState = "closed"
	ListOrgProjectsParamsStateOpen   ListOrgProjectsParamsState = "open"
)

// Defines values for ListOrgProjectsParamsSort.
const (
	ListOrgProjectsParamsSortAlphabetically        ListOrgProjectsParamsSort = "alphabetically"
	ListOrgProjectsParamsSortLeastupdate           ListOrgProjectsParamsSort = "leastupdate"
	ListOrgProjectsParamsSortNewest                ListOrgProjectsParamsSort = "newest"
	ListOrgProjectsParamsSortOldest                ListOrgProjectsParamsSort = "oldest"
	ListOrgProjectsParamsSortRecentupdate          ListOrgProjectsParamsSort = "recentupdate"
	ListOrgProjectsParamsSortReversealphabetically ListOrgProjectsParamsSort = "reversealphabetically"
)

// Defines values for ListRepoProjectsParamsState.
const (
	All    ListRepoProjectsParamsState = "all"
	Closed ListRepoProjectsParamsState = "closed"
	Open   ListRepoProjectsParamsState = "open"
)

// Defines values for ListRepoProjectsParamsSort.
const (
	Alphabetically        ListRepoProjectsParamsSort = "alphabetically"
	Leastupdate           ListRepoProjectsParamsSort = "leastupdate"
	Newest                ListRepoProjectsParamsSort = "newest"
	Oldest                ListRepoProjectsParamsSort = "oldest"
	Recentupdate          ListRepoProjectsParamsSort = "recentupdate"
	Reversealphabetically ListRepoProjectsParamsSort = "reversealphabetically"
)

// APIError defines model for APIError.
type APIError struct {
	Message *string `json:"message,omitempty"`
	Url     *string `json:"url,omitempty"`
}

// AddCardOption defines model for AddCardOption.
type AddCardOption struct {
	IssueId  int64  `json:"issue_id"`
	Position *int64 `json:"position,omitempty"`
}

// CardPosition defines model for CardPosition.
type CardPosition struct {
	CardId   int64 `json:"card_id"`
	Position int64 `json:"position"`
}

// ColumnPosition defines model for ColumnPosition.
type ColumnPosition struct {
	ColumnId int64 `json:"column_id"`
	Position int   `json:"position"`
}

// CreateColumnOption defines model for CreateColumnOption.
type CreateColumnOption struct {
	Color *string `json:"color,omitempty"`
	Title string  `json:"title"`
}

// CreateProjectOption defines model for CreateProjectOption.
type CreateProjectOption struct {
	Body *string `json:"body,omitempty"`

	// TemplateType 0=none, 1=basic kanban, 2=bug triage
	TemplateType *int   `json:"template_type,omitempty"`
	Title        string `json:"title"`
}

// EditColumnOption defines model for EditColumnOption.
type EditColumnOption struct {
	Color *string `json:"color,omitempty"`
	Title *string `json:"title,omitempty"`
}

// EditProjectOption defines model for EditProjectOption.
type EditProjectOption struct {
	Body *string `json:"body,omitempty"`

	// CardType 0=text only, 1=images and text
	CardType *int                    `json:"card_type,omitempty"`
	State    *EditProjectOptionState `json:"state,omitempty"`
	Title    *string                 `json:"title,omitempty"`
}

// EditProjectOptionState defines model for EditProjectOption.State.
type EditProjectOptionState string

// MoveCardOption defines model for MoveCardOption.
type MoveCardOption struct {
	ColumnId *int64 `json:"column_id,omitempty"`
	Position *int64 `json:"position,omitempty"`
}

// MoveColumnsOption defines model for MoveColumnsOption.
type MoveColumnsOption struct {
	Columns []ColumnPosition `json:"columns"`
}

// Project defines model for Project.
type Project struct {
	Body *string `json:"body,omitempty"`

	// CardType 0=text only, 1=images and text
	CardType     *int          `json:"card_type,omitempty"`
	ClosedAt     *time.Time    `json:"closed_at"`
	ClosedIssues *int          `json:"closed_issues,omitempty"`
	ColumnCount  *int          `json:"column_count,omitempty"`
	CreatedAt    *time.Time    `json:"created_at,omitempty"`
	Id           *int64        `json:"id,omitempty"`
	OpenIssues   *int          `json:"open_issues,omitempty"`
	State        *ProjectState `json:"state,omitempty"`

	// TemplateType 0=none, 1=basic kanban, 2=bug triage
	TemplateType *int    `json:"template_type,omitempty"`
	Title        *string `json:"title,omitempty"`

	// Type 1=individual, 2=repository, 3=organization
	Type      *int       `json:"type,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ProjectState defines model for Project.State.
type ProjectState string

// ProjectCard defines model for ProjectCard.
type ProjectCard struct {
	Column *ProjectColumn `json:"column,omitempty"`
	Id     *int64         `json:"id,omitempty"`

	// Issue Minimal issue info embedded in a project card
	Issue   *ProjectCardIssue `json:"issue,omitempty"`
	Sorting *int64            `json:"sorting,omitempty"`
}

// ProjectCardIssue Minimal issue info embedded in a project card
type ProjectCardIssue struct {
	Id     *int64  `json:"id,omitempty"`
	IsPull *bool   `json:"is_pull,omitempty"`
	Number *int64  `json:"number,omitempty"`
	State  *string `json:"state,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// ProjectColumn defines model for ProjectColumn.
type ProjectColumn struct {
	CardCount *int       `json:"card_count,omitempty"`
	Color     *string    `json:"color,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Default   *bool      `json:"default,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Sorting   *int       `json:"sorting,omitempty"`
	Title     *string    `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ReorderCardsOption defines model for ReorderCardsOption.
type ReorderCardsOption struct {
	CardPositions []CardPosition `json:"card_positions"`
}

// Version defines model for Version.
type Version struct {
	Version *string `json:"version,omitempty"`
}

// Card defines model for card.
type Card = int64

// Column defines model for column.
type Column = int64

// Keyword defines model for keyword.
type Keyword = string

// Limit defines model for limit.
type Limit = int

// Org defines model for org.
type Org = string

// Owner defines model for owner.
type Owner = string

// Page defines model for page.
type Page = int

// ProjectId defines model for projectId.
type ProjectId = int64

// Repo defines model for repo.
type Repo = string

// Sort defines model for sort.
type Sort string

// State defines model for state.
type State string

// Conflict defines model for Conflict.
type Conflict = APIError

// Forbidden defines model for Forbidden.
type Forbidden = APIError

// NotFound defines model for NotFound.
type NotFound = APIError

// ProjectCardList defines model for ProjectCardList.
type ProjectCardList = []ProjectCard

// ProjectColumnList defines model for ProjectColumnList.
type ProjectColumnList = []ProjectColumn

// ProjectList defines model for ProjectList.
type ProjectList = []Project

// ValidationError defines model for ValidationError.
type ValidationError = APIError

// ListOrgProjectsParams defines parameters for ListOrgProjects.
type ListOrgProjectsParams struct {
	// State filter by project state
	State *ListOrgProjectsParamsState `form:"state,omitempty" json:"state,omitempty"`

	// Keyword search projects by title keyword
	Keyword *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`

	// Sort sort order
	Sort *ListOrgProjectsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page page number of results to return (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit page size of results
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrgProjectsParamsState defines parameters for ListOrgProjects.
type ListOrgProjectsParamsState string

// ListOrgProjectsParamsSort defines parameters for ListOrgProjects.
type ListOrgProjectsParamsSort string

// ListOrgProjectCardsParams defines parameters for ListOrgProjectCards.
type ListOrgProjectCardsParams struct {
	// Page page number of results to return (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit page size of results
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRepoProjectsParams defines parameters for ListRepoProjects.
type ListRepoProjectsParams struct {
	// State filter by project state
	State *ListRepoProjectsParamsState `form:"state,omitempty" json:"state,omitempty"`

	// Keyword search projects by title keyword
	Keyword *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`

	// Sort sort order
	Sort *ListRepoProjectsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page page number of results to return (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit page size of results
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRepoProjectsParamsState defines parameters for ListRepoProjects.
type ListRepoProjectsParamsState string

// ListRepoProjectsParamsSort defines parameters for ListRepoProjects.
type ListRepoProjectsParamsSort string

// ListRepoProjectCardsParams defines parameters for ListRepoProjectCards.
type ListRepoProjectCardsParams struct {
	// Page page number of results to return (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit page size of results
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrgProjectJSONRequestBody defines body for CreateOrgProject for application/json ContentType.
type CreateOrgProjectJSONRequestBody = CreateProjectOption

// UpdateOrgProjectJSONRequestBody defines body for UpdateOrgProject for application/json ContentType.
type UpdateOrgProjectJSONRequestBody = EditProjectOption

// MoveOrgProjectCardJSONRequestBody defines body for MoveOrgProjectCard for application/json ContentType.
type MoveOrgProjectCardJSONRequestBody = MoveCardOption

// CreateOrgProjectColumnJSONRequestBody defines body for CreateOrgProjectColumn for application/json ContentType.
type CreateOrgProjectColumnJSONRequestBody = CreateColumnOption

// MoveOrgProjectColumnsJSONRequestBody defines body for MoveOrgProjectColumns for application/json ContentType.
type MoveOrgProjectColumnsJSONRequestBody = MoveColumnsOption

// UpdateOrgProjectColumnJSONRequestBody defines body for UpdateOrgProjectColumn for application/json ContentType.
type UpdateOrgProjectColumnJSONRequestBody = EditColumnOption

// AddOrgProjectCardJSONRequestBody defines body for AddOrgProjectCard for application/json ContentType.
type AddOrgProjectCardJSONRequestBody = AddCardOption

// ReorderOrgProjectCardsJSONRequestBody defines body for ReorderOrgProjectCards for application/json ContentType.
type ReorderOrgProjectCardsJSONRequestBody = ReorderCardsOption

// CreateRepoProjectJSONRequestBody defines body for CreateRepoProject for application/json ContentType.
type CreateRepoProjectJSONRequestBody = CreateProjectOption

// UpdateRepoProjectJSONRequestBody defines body for UpdateRepoProject for application/json ContentType.
type UpdateRepoProjectJSONRequestBody = EditProjectOption

// MoveRepoProjectCardJSONRequestBody defines body for MoveRepoProjectCard for application/json ContentType.
type MoveRepoProjectCardJSONRequestBody = MoveCardOption

// CreateRepoProjectColumnJSONRequestBody defines body for CreateRepoProjectColumn for application/json ContentType.
type CreateRepoProjectColumnJSONRequestBody = CreateColumnOption

// MoveRepoProjectColumnsJSONRequestBody defines body for MoveRepoProjectColumns for application/json ContentType.
type MoveRepoProjectColumnsJSONRequestBody = MoveColumnsOption

// UpdateRepoProjectColumnJSONRequestBody defines body for UpdateRepoProjectColumn for application/json ContentType.
type UpdateRepoProjectColumnJSONRequestBody = EditColumnOption

// AddRepoProjectCardJSONRequestBody defines body for AddRepoProjectCard for application/json ContentType.
type AddRepoProjectCardJSONRequestBody = AddCardOption

// ReorderRepoProjectCardsJSONRequestBody defines body for ReorderRepoProjectCards for application/json ContentType.
type ReorderRepoProjectCardsJSONRequestBody = ReorderCardsOption

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List organization projects
	// (GET /orgs/{org}/projects)
	ListOrgProjects(w http.ResponseWriter, r *http.Request, org Org, params ListOrgProjectsParams)
	// Create an organization project
	// (POST /orgs/{org}/projects)
	CreateOrgProject(w http.ResponseWriter, r *http.Request, org Org)
	// Delete an organization project
	// (DELETE /orgs/{org}/projects/{project})
	DeleteOrgProject(w http.ResponseWriter, r *http.Request, org Org, project ProjectId)
	// Get an organization project
	// (GET /orgs/{org}/projects/{project})
	GetOrgProject(w http.ResponseWriter, r *http.Request, org Org, project ProjectId)
	// Update an organization project
	// (PATCH /orgs/{org}/projects/{project})
	UpdateOrgProject(w http.ResponseWriter, r *http.Request, org Org, project ProjectId)
	// Remove a card from an organization project
	// (DELETE /orgs/{org}/projects/{project}/cards/{card})
	DeleteOrgProjectCard(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, card Card)
	// Move an organization project card
	// (PATCH /orgs/{org}/projects/{project}/cards/{card})
	MoveOrgProjectCard(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, card Card)
	// List organization project columns
	// (GET /orgs/{org}/projects/{project}/columns)
	ListOrgProjectColumns(w http.ResponseWriter, r *http.Request, org Org, project ProjectId)
	// Create an organization project column
	// (POST /orgs/{org}/projects/{project}/columns)
	CreateOrgProjectColumn(w http.ResponseWriter, r *http.Request, org Org, project ProjectId)
	// Reorder organization project columns
	// (POST /orgs/{org}/projects/{project}/columns/move)
	MoveOrgProjectColumns(w http.ResponseWriter, r *http.Request, org Org, project ProjectId)
	// Delete an organization project column
	// (DELETE /orgs/{org}/projects/{project}/columns/{column})
	DeleteOrgProjectColumn(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column)
	// Update an organization project column
	// (PATCH /orgs/{org}/projects/{project}/columns/{column})
	UpdateOrgProjectColumn(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column)
	// List cards in an organization project column
	// (GET /orgs/{org}/projects/{project}/columns/{column}/cards)
	ListOrgProjectCards(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column, params ListOrgProjectCardsParams)
	// Add a card to an organization project column
	// (POST /orgs/{org}/projects/{project}/columns/{column}/cards)
	AddOrgProjectCard(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column)
	// Reorder cards in an organization project column
	// (PATCH /orgs/{org}/projects/{project}/columns/{column}/cards/reorder)
	ReorderOrgProjectCards(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column)
	// List repository projects
	// (GET /repos/{owner}/{repo}/projects)
	ListRepoProjects(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, params ListRepoProjectsParams)
	// Create a repository project
	// (POST /repos/{owner}/{repo}/projects)
	CreateRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo)
	// Delete a repository project
	// (DELETE /repos/{owner}/{repo}/projects/{project})
	DeleteRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId)
	// Get a repository project
	// (GET /repos/{owner}/{repo}/projects/{project})
	GetRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId)
	// Update a repository project
	// (PATCH /repos/{owner}/{repo}/projects/{project})
	UpdateRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId)
	// Remove a card from a project
	// (DELETE /repos/{owner}/{repo}/projects/{project}/cards/{card})
	DeleteRepoProjectCard(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, card Card)
	// Move a project card
	// (PATCH /repos/{owner}/{repo}/projects/{project}/cards/{card})
	MoveRepoProjectCard(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, card Card)
	// List project columns
	// (GET /repos/{owner}/{repo}/projects/{project}/columns)
	ListRepoProjectColumns(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId)
	// Create a project column
	// (POST /repos/{owner}/{repo}/projects/{project}/columns)
	CreateRepoProjectColumn(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId)
	// Reorder project columns
	// (POST /repos/{owner}/{repo}/projects/{project}/columns/move)
	MoveRepoProjectColumns(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId)
	// Delete a project column
	// (DELETE /repos/{owner}/{repo}/projects/{project}/columns/{column})
	DeleteRepoProjectColumn(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column)
	// Update a project column
	// (PATCH /repos/{owner}/{repo}/projects/{project}/columns/{column})
	UpdateRepoProjectColumn(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column)
	// List cards in a project column
	// (GET /repos/{owner}/{repo}/projects/{project}/columns/{column}/cards)
	ListRepoProjectCards(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column, params ListRepoProjectCardsParams)
	// Add a card to a project column
	// (POST /repos/{owner}/{repo}/projects/{project}/columns/{column}/cards)
	AddRepoProjectCard(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column)
	// Reorder cards in a project column
	// (PATCH /repos/{owner}/{repo}/projects/{project}/columns/{column}/cards/reorder)
	ReorderRepoProjectCards(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column)
	// API version
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List organization projects
// (GET /orgs/{org}/projects)
func (_ Unimplemented) ListOrgProjects(w http.ResponseWriter, r *http.Request, org Org, params ListOrgProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organization project
// (POST /orgs/{org}/projects)
func (_ Unimplemented) CreateOrgProject(w http.ResponseWriter, r *http.Request, org Org) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an organization project
// (DELETE /orgs/{org}/projects/{project})
func (_ Unimplemented) DeleteOrgProject(w http.ResponseWriter, r *http.Request, org Org, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an organization project
// (GET /orgs/{org}/projects/{project})
func (_ Unimplemented) GetOrgProject(w http.ResponseWriter, r *http.Request, org Org, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an organization project
// (PATCH /orgs/{org}/projects/{project})
func (_ Unimplemented) UpdateOrgProject(w http.ResponseWriter, r *http.Request, org Org, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a card from an organization project
// (DELETE /orgs/{org}/projects/{project}/cards/{card})
func (_ Unimplemented) DeleteOrgProjectCard(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, card Card) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Move an organization project card
// (PATCH /orgs/{org}/projects/{project}/cards/{card})
func (_ Unimplemented) MoveOrgProjectCard(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, card Card) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List organization project columns
// (GET /orgs/{org}/projects/{project}/columns)
func (_ Unimplemented) ListOrgProjectColumns(w http.ResponseWriter, r *http.Request, org Org, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organization project column
// (POST /orgs/{org}/projects/{project}/columns)
func (_ Unimplemented) CreateOrgProjectColumn(w http.ResponseWriter, r *http.Request, org Org, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder organization project columns
// (POST /orgs/{org}/projects/{project}/columns/move)
func (_ Unimplemented) MoveOrgProjectColumns(w http.ResponseWriter, r *http.Request, org Org, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an organization project column
// (DELETE /orgs/{org}/projects/{project}/columns/{column})
func (_ Unimplemented) DeleteOrgProjectColumn(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an organization project column
// (PATCH /orgs/{org}/projects/{project}/columns/{column})
func (_ Unimplemented) UpdateOrgProjectColumn(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List cards in an organization project column
// (GET /orgs/{org}/projects/{project}/columns/{column}/cards)
func (_ Unimplemented) ListOrgProjectCards(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column, params ListOrgProjectCardsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a card to an organization project column
// (POST /orgs/{org}/projects/{project}/columns/{column}/cards)
func (_ Unimplemented) AddOrgProjectCard(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder cards in an organization project column
// (PATCH /orgs/{org}/projects/{project}/columns/{column}/cards/reorder)
func (_ Unimplemented) ReorderOrgProjectCards(w http.ResponseWriter, r *http.Request, org Org, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List repository projects
// (GET /repos/{owner}/{repo}/projects)
func (_ Unimplemented) ListRepoProjects(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, params ListRepoProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a repository project
// (POST /repos/{owner}/{repo}/projects)
func (_ Unimplemented) CreateRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a repository project
// (DELETE /repos/{owner}/{repo}/projects/{project})
func (_ Unimplemented) DeleteRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a repository project
// (GET /repos/{owner}/{repo}/projects/{project})
func (_ Unimplemented) GetRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a repository project
// (PATCH /repos/{owner}/{repo}/projects/{project})
func (_ Unimplemented) UpdateRepoProject(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a card from a project
// (DELETE /repos/{owner}/{repo}/projects/{project}/cards/{card})
func (_ Unimplemented) DeleteRepoProjectCard(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, card Card) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Move a project card
// (PATCH /repos/{owner}/{repo}/projects/{project}/cards/{card})
func (_ Unimplemented) MoveRepoProjectCard(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, card Card) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List project columns
// (GET /repos/{owner}/{repo}/projects/{project}/columns)
func (_ Unimplemented) ListRepoProjectColumns(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a project column
// (POST /repos/{owner}/{repo}/projects/{project}/columns)
func (_ Unimplemented) CreateRepoProjectColumn(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder project columns
// (POST /repos/{owner}/{repo}/projects/{project}/columns/move)
func (_ Unimplemented) MoveRepoProjectColumns(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a project column
// (DELETE /repos/{owner}/{repo}/projects/{project}/columns/{column})
func (_ Unimplemented) DeleteRepoProjectColumn(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a project column
// (PATCH /repos/{owner}/{repo}/projects/{project}/columns/{column})
func (_ Unimplemented) UpdateRepoProjectColumn(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List cards in a project column
// (GET /repos/{owner}/{repo}/projects/{project}/columns/{column}/cards)
func (_ Unimplemented) ListRepoProjectCards(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column, params ListRepoProjectCardsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a card to a project column
// (POST /repos/{owner}/{repo}/projects/{project}/columns/{column}/cards)
func (_ Unimplemented) AddRepoProjectCard(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder cards in a project column
// (PATCH /repos/{owner}/{repo}/projects/{project}/columns/{column}/cards/reorder)
func (_ Unimplemented) ReorderRepoProjectCards(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo, project ProjectId, column Column) {
	w.WriteHeader(http.StatusNotImplemented)
}

// API version
// (GET /version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOrgProjects operation middleware
func (siw *ServerInterfaceWrapper) ListOrgProjects(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrgProjectsParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "keyword" -------------

	err = runtime.BindQueryParameter("form", true, false, "keyword", r.URL.Query(), &params.Keyword)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyword", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrgProjects(w, r, org, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrgProject operation middleware
func (siw *ServerInterfaceWrapper) CreateOrgProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrgProject(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrgProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrgProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrgProject(w, r, org, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrgProject operation middleware
func (siw *ServerInterfaceWrapper) GetOrgProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrgProject(w, r, org, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrgProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrgProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrgProject(w, r, org, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrgProjectCard operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrgProjectCard(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "card" -------------
	var card Card

	err = runtime.BindStyledParameterWithOptions("simple", "card", chi.URLParam(r, "card"), &card, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "card", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrgProjectCard(w, r, org, project, card)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveOrgProjectCard operation middleware
func (siw *ServerInterfaceWrapper) MoveOrgProjectCard(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "card" -------------
	var card Card

	err = runtime.BindStyledParameterWithOptions("simple", "card", chi.URLParam(r, "card"), &card, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "card", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveOrgProjectCard(w, r, org, project, card)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrgProjectColumns operation middleware
func (siw *ServerInterfaceWrapper) ListOrgProjectColumns(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrgProjectColumns(w, r, org, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrgProjectColumn operation middleware
func (siw *ServerInterfaceWrapper) CreateOrgProjectColumn(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrgProjectColumn(w, r, org, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveOrgProjectColumns operation middleware
func (siw *ServerInterfaceWrapper) MoveOrgProjectColumns(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveOrgProjectColumns(w, r, org, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrgProjectColumn operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrgProjectColumn(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrgProjectColumn(w, r, org, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrgProjectColumn operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrgProjectColumn(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrgProjectColumn(w, r, org, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrgProjectCards operation middleware
func (siw *ServerInterfaceWrapper) ListOrgProjectCards(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrgProjectCardsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrgProjectCards(w, r, org, project, column, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddOrgProjectCard operation middleware
func (siw *ServerInterfaceWrapper) AddOrgProjectCard(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddOrgProjectCard(w, r, org, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderOrgProjectCards operation middleware
func (siw *ServerInterfaceWrapper) ReorderOrgProjectCards(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "org" -------------
	var org Org

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderOrgProjectCards(w, r, org, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepoProjects operation middleware
func (siw *ServerInterfaceWrapper) ListRepoProjects(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRepoProjectsParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "keyword" -------------

	err = runtime.BindQueryParameter("form", true, false, "keyword", r.URL.Query(), &params.Keyword)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyword", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepoProjects(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRepoProject operation middleware
func (siw *ServerInterfaceWrapper) CreateRepoProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRepoProject(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRepoProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteRepoProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRepoProject(w, r, owner, repo, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepoProject operation middleware
func (siw *ServerInterfaceWrapper) GetRepoProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepoProject(w, r, owner, repo, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRepoProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateRepoProject(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRepoProject(w, r, owner, repo, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRepoProjectCard operation middleware
func (siw *ServerInterfaceWrapper) DeleteRepoProjectCard(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "card" -------------
	var card Card

	err = runtime.BindStyledParameterWithOptions("simple", "card", chi.URLParam(r, "card"), &card, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "card", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRepoProjectCard(w, r, owner, repo, project, card)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveRepoProjectCard operation middleware
func (siw *ServerInterfaceWrapper) MoveRepoProjectCard(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "card" -------------
	var card Card

	err = runtime.BindStyledParameterWithOptions("simple", "card", chi.URLParam(r, "card"), &card, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "card", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveRepoProjectCard(w, r, owner, repo, project, card)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepoProjectColumns operation middleware
func (siw *ServerInterfaceWrapper) ListRepoProjectColumns(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepoProjectColumns(w, r, owner, repo, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRepoProjectColumn operation middleware
func (siw *ServerInterfaceWrapper) CreateRepoProjectColumn(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRepoProjectColumn(w, r, owner, repo, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveRepoProjectColumns operation middleware
func (siw *ServerInterfaceWrapper) MoveRepoProjectColumns(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveRepoProjectColumns(w, r, owner, repo, project)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRepoProjectColumn operation middleware
func (siw *ServerInterfaceWrapper) DeleteRepoProjectColumn(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRepoProjectColumn(w, r, owner, repo, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRepoProjectColumn operation middleware
func (siw *ServerInterfaceWrapper) UpdateRepoProjectColumn(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRepoProjectColumn(w, r, owner, repo, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepoProjectCards operation middleware
func (siw *ServerInterfaceWrapper) ListRepoProjectCards(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRepoProjectCardsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepoProjectCards(w, r, owner, repo, project, column, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddRepoProjectCard operation middleware
func (siw *ServerInterfaceWrapper) AddRepoProjectCard(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddRepoProjectCard(w, r, owner, repo, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderRepoProjectCards operation middleware
func (siw *ServerInterfaceWrapper) ReorderRepoProjectCards(w http.ResponseWriter, r *http.Request) {
	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "project" -------------
	var project ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "project", chi.URLParam(r, "project"), &project, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project", Err: err})
		return
	}

	// ------------- Path parameter "column" -------------
	var column Column

	err = runtime.BindStyledParameterWithOptions("simple", "column", chi.URLParam(r, "column"), &column, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "column", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderRepoProjectCards(w, r, owner, repo, project, column)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org}/projects", wrapper.ListOrgProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/{org}/projects", wrapper.CreateOrgProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/orgs/{org}/projects/{project}", wrapper.DeleteOrgProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org}/projects/{project}", wrapper.GetOrgProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/orgs/{org}/projects/{project}", wrapper.UpdateOrgProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/orgs/{org}/projects/{project}/cards/{card}", wrapper.DeleteOrgProjectCard)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/orgs/{org}/projects/{project}/cards/{card}", wrapper.MoveOrgProjectCard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org}/projects/{project}/columns", wrapper.ListOrgProjectColumns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/{org}/projects/{project}/columns", wrapper.CreateOrgProjectColumn)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/{org}/projects/{project}/columns/move", wrapper.MoveOrgProjectColumns)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/orgs/{org}/projects/{project}/columns/{column}", wrapper.DeleteOrgProjectColumn)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/orgs/{org}/projects/{project}/columns/{column}", wrapper.UpdateOrgProjectColumn)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org}/projects/{project}/columns/{column}/cards", wrapper.ListOrgProjectCards)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/{org}/projects/{project}/columns/{column}/cards", wrapper.AddOrgProjectCard)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/orgs/{org}/projects/{project}/columns/{column}/cards/reorder", wrapper.ReorderOrgProjectCards)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/repos/{owner}/{repo}/projects", wrapper.ListRepoProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/repos/{owner}/{repo}/projects", wrapper.CreateRepoProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}", wrapper.DeleteRepoProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}", wrapper.GetRepoProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}", wrapper.UpdateRepoProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/cards/{card}", wrapper.DeleteRepoProjectCard)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/cards/{card}", wrapper.MoveRepoProjectCard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns", wrapper.ListRepoProjectColumns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns", wrapper.CreateRepoProjectColumn)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns/move", wrapper.MoveRepoProjectColumns)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns/{column}", wrapper.DeleteRepoProjectColumn)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns/{column}", wrapper.UpdateRepoProjectColumn)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns/{column}/cards", wrapper.ListRepoProjectCards)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns/{column}/cards", wrapper.AddRepoProjectCard)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/repos/{owner}/{repo}/projects/{project}/columns/{column}/cards/reorder", wrapper.ReorderRepoProjectCards)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}
