// Copyright 2026 The Forgejo Authors. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-or-later

package snippet

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	snippet_model "forgejo.org/models/snippet"

	"forgejo.org/models/db"
	"forgejo.org/modules/log"
	"forgejo.org/modules/setting"
	"forgejo.org/modules/util"
	"xorm.io/builder"
)

const (
	EnvSnippetUUID = "FORGEJO_SNIPPET_UUID"
)

// SetupSnippetHooks creates the Snippet Hook
func SetupSnippetHooks(path string) error {
	err := os.Mkdir(filepath.Join(path, "hooks"), 0o750)
	if err != nil && !os.IsExist(err) {
		return err
	}

	preHookContent := fmt.Sprintf("#!/usr/bin/env %s\n# AUTO GENERATED BY FORGEJO, DO NOT MODIFY\n%s hook --config=%s snippet-pre-receive",
		setting.ScriptType, util.ShellEscape(setting.AppPath), util.ShellEscape(setting.CustomConf))

	err = os.WriteFile(filepath.Join(path, "hooks", "pre-receive"), []byte(preHookContent), 0o777)
	if err != nil {
		return err
	}

	postHookContent := fmt.Sprintf("#!/usr/bin/env %s\n# AUTO GENERATED BY FORGEJO, DO NOT MODIFY\n%s hook --config=%s snippet-post-receive",
		setting.ScriptType, util.ShellEscape(setting.AppPath), util.ShellEscape(setting.CustomConf))

	err = os.WriteFile(filepath.Join(path, "hooks", "post-receive"), []byte(postHookContent), 0o777)
	if err != nil {
		return err
	}

	return nil
}

// SyncSnippetHooks rewrites all snippets' pre-receive and post-receive hooks
// to make sure the binary and custom conf path are up-to-date.
func SyncSnippetHooks(ctx context.Context) error {
	log.Trace("Doing: SyncSnippetHooks")

	if err := db.Iterate(
		ctx,
		builder.Gt{"id": 0},
		func(ctx context.Context, snippet *snippet_model.Snippet) error {
			select {
			case <-ctx.Done():
				return db.ErrCancelledf("before sync snippet hooks for %s", snippet.UUID)
			default:
			}

			if err := SetupSnippetHooks(snippet.GetRepoPath()); err != nil {
				return fmt.Errorf("SetupSnippetHooks: %w", err)
			}

			return nil
		},
	); err != nil {
		return err
	}

	log.Trace("Finished: SyncSnippetHooks")
	return nil
}
