// Copyright 2026 The Forgejo Authors. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-or-later

package snippet

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"forgejo.org/models/db"
	repo_model "forgejo.org/models/repo"
	snippet_model "forgejo.org/models/snippet"
	user_model "forgejo.org/models/user"
	"forgejo.org/modules/git"
	"forgejo.org/modules/setting"
	api "forgejo.org/modules/structs"
	"forgejo.org/modules/util"
)

const (
	SnippetBranch = "main"
)

// SetupSnippetHook creates the Snippet Hook
func SetupSnippetHook(path string) error {
	err := os.Mkdir(filepath.Join(path, "hooks"), 0o750)
	if err != nil && !os.IsExist(err) {
		return err
	}

	hookContent := fmt.Sprintf("#!/usr/bin/env %s\n# AUTO GENERATED BY FORGEJO, DO NOT MODIFY\n%s hook --config=%s snippet-pre-receive",
		setting.ScriptType, util.ShellEscape(setting.AppPath), util.ShellEscape(setting.CustomConf))

	err = os.WriteFile(filepath.Join(path, "hooks", "pre-receive"), []byte(hookContent), 0o777)
	if err != nil {
		return err
	}

	return nil
}

// CreateSnippet creates a Snippet
func CreateSnippet(ctx context.Context, owner *user_model.User, name, description string, visibility snippet_model.SnippetVisibility, files SnippetFiles) (*snippet_model.Snippet, error) {
	err := files.ValidateNames()
	if err != nil {
		return nil, err
	}

	tempDir, err := os.MkdirTemp("", "")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tempDir)

	err = git.InitRepository(ctx, tempDir, git.InitRepositoryOptions{Bare: false, ObjectFormatName: git.Sha1ObjectFormat.Name(), Branch: SnippetBranch})
	if err != nil {
		return nil, err
	}

	nameList := make([]string, 0)
	for _, currentFile := range files {
		err := os.WriteFile(filepath.Join(tempDir, currentFile.Name), []byte(currentFile.Content), 0o644)
		if err != nil {
			return nil, err
		}

		nameList = append(nameList, currentFile.Name)
	}

	err = git.AddChanges(tempDir, false, nameList...)
	if err != nil {
		return nil, err
	}

	err = git.CommitChanges(tempDir, git.CommitChangesOptions{
		Author:    &git.Signature{Name: owner.Name, Email: owner.Email},
		Committer: &git.Signature{Name: owner.Name, Email: owner.Email},
		Message:   "Init",
	})
	if err != nil {
		return nil, err
	}

	ctx, committer, err := db.TxContext(ctx)
	if err != nil {
		return nil, err
	}
	defer committer.Close()

	snippet := new(snippet_model.Snippet)
	snippet.Owner = owner
	snippet.OwnerID = owner.ID
	snippet.Name = name
	snippet.Description = description
	snippet.Visibility = visibility
	snippet.Language = files.GetLanguage()

	err = snippet_model.Create(ctx, snippet)
	if err != nil {
		return nil, err
	}

	err = git.InitRepository(ctx, snippet.GetRepoPath(), git.InitRepositoryOptions{Bare: true, Branch: SnippetBranch, ObjectFormatName: git.Sha1ObjectFormat.Name()})
	if err != nil {
		return nil, err
	}

	cmd := git.NewCommand(ctx, "push", "--set-upstream")
	cmd.AddDynamicArguments(snippet.GetRepoPath())
	cmd.AddDynamicArguments(SnippetBranch)
	_, _, err = cmd.RunStdString(&git.RunOpts{Dir: tempDir})
	if err != nil {
		os.RemoveAll(snippet.GetRepoPath())
		return nil, err
	}

	err = SetupSnippetHook(snippet.GetRepoPath())
	if err != nil {
		os.RemoveAll(snippet.GetRepoPath())
		return nil, err
	}

	err = committer.Commit()
	if err != nil {
		return nil, err
	}

	return snippet, nil
}

// GetFiles returns the files of a Snippet
func GetFiles(ctx context.Context, snippet *snippet_model.Snippet) (SnippetFiles, error) {
	repo, err := git.OpenRepository(ctx, snippet.GetRepoPath())
	if err != nil {
		return nil, err
	}
	defer repo.Close()

	branch, err := repo.GetBranch(SnippetBranch)
	if err != nil {
		return nil, err
	}

	commit, err := branch.GetCommit()
	if err != nil {
		return nil, err
	}

	entries, err := commit.ListEntries()
	if err != nil {
		return nil, err
	}

	files := make([]*api.SnippetFile, len(entries))

	for pos, currentEntry := range entries {
		reader, err := currentEntry.Blob().DataAsync()
		if err != nil {
			return nil, err
		}
		defer reader.Close()

		content, err := io.ReadAll(reader)
		if err != nil {
			return nil, err
		}

		currentFile := new(api.SnippetFile)
		currentFile.Name = currentEntry.Name()
		currentFile.Content = string(content)

		files[pos] = currentFile
	}

	return files, nil
}

// GetBlob returns a blob of a Snippet file
func GetBlob(ctx context.Context, snippet *snippet_model.Snippet, filename string) (*git.Blob, error) {
	repo, err := git.OpenRepository(ctx, snippet.GetRepoPath())
	if err != nil {
		return nil, err
	}
	defer repo.Close()

	branch, err := repo.GetBranch(SnippetBranch)
	if err != nil {
		return nil, err
	}

	commit, err := branch.GetCommit()
	if err != nil {
		return nil, err
	}

	return commit.GetBlobByPath(filename)
}

// UpdateFiles replaces the files of a Snippet
func UpdateFiles(ctx context.Context, snippet *snippet_model.Snippet, doer *user_model.User, files SnippetFiles) error {
	for _, currentFile := range files {
		if util.PathContainsDirectory(currentFile.Name) {
			return fmt.Errorf("%s contains a directory", currentFile.Name)
		}
	}

	tempDir, err := os.MkdirTemp("", "")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tempDir)

	oldFiles, err := GetFiles(ctx, snippet)
	if err != nil {
		return err
	}

	err = git.Clone(ctx, snippet.GetRepoPath(), tempDir, git.CloneRepoOptions{})
	if err != nil {
		return err
	}

	// Delete files that are no longer in the Snippet
	missingFiles := make([]string, 0)
	for _, currentOldFile := range oldFiles {
		if !files.Contains(currentOldFile.Name) {
			missingFiles = append(missingFiles, currentOldFile.Name)
		}
	}

	if len(missingFiles) > 0 {
		err = git.RemoveFiles(tempDir, missingFiles...)
		if err != nil {
			return err
		}
	}

	changedFiles := make([]string, 0)
	for _, currentFile := range files {
		err := os.WriteFile(filepath.Join(tempDir, currentFile.Name), []byte(currentFile.Content), 0o644)
		if err != nil {
			return err
		}

		changedFiles = append(changedFiles, currentFile.Name)
	}

	err = git.AddChanges(tempDir, false, changedFiles...)
	if err != nil {
		return err
	}

	err = git.CommitChanges(tempDir, git.CommitChangesOptions{
		Author:    &git.Signature{Name: doer.Name, Email: doer.Email},
		Committer: &git.Signature{Name: doer.Name, Email: doer.Email},
		Message:   "Update",
	})
	if err != nil {
		return err
	}

	err = git.Push(ctx, tempDir, git.PushOptions{
		Remote: snippet.GetRepoPath(),
	})
	if err != nil {
		return err
	}

	// Update the language
	snippet.Language = files.GetLanguage()
	err = snippet.UpdateCols(ctx, "language")
	if err != nil {
		return err
	}

	return nil
}

// DeleteSnippet deletes a Snippet
func DeleteSnippet(ctx context.Context, snippet *snippet_model.Snippet) error {
	ctx, committer, err := db.TxContext(ctx)
	if err != nil {
		return err
	}
	defer committer.Close()

	_, err = db.GetEngine(ctx).Exec("DELETE FROM snippet WHERE id = ?", snippet.ID)
	if err != nil {
		return err
	}

	err = os.RemoveAll(snippet.GetRepoPath())
	if err != nil {
		return err
	}

	return committer.Commit()
}

func DeleteOwnerSnippets(ctx context.Context, owner *user_model.User) error {
	for {
		snippetList := make(snippet_model.SnippetList, 0)

		err := db.GetEngine(ctx).Where("owner_id = ?", owner.ID).Limit(repo_model.RepositoryListDefaultPageSize).Find(&snippetList)
		if err != nil {
			return err
		}

		if len(snippetList) == 0 {
			return nil
		}

		for _, snippet := range snippetList {
			err = DeleteSnippet(ctx, snippet)
			if err != nil {
				return err
			}
		}
	}
}
